---
- name: Update Mac Config
  hosts: all
  tasks:

  - name: Install homebrew packages
    homebrew:
      name: mas
      state: latest
    tags:
    - brew

  - name: Install MAS apps
    community.general.mas:
      id:
        - 747648890 # Telegram
        - 1485052491 # Dropzone 4
      state: present
