---
- name: Update Mac Config
  hosts: all
  tasks:

  - name: Install homebrew packages
    homebrew:
      name: "{{ item }}"
      state: latest
    with_items:
      - mas
    tags:
    - brew
  
  - name: Install via brew cask
    homebrew_cask: 
      name: "{{ item }}"
    with_items:
      - discord


