---
- name: Update Mac Config
  hosts: all
  roles:
    - brew
  tasks:

  - name: Install homebrew packages
    homebrew:
      name: mas
      state: latest
    tags:
    - brew
  
  - name: Install via brew cask
    homebrew_cask: 
      name: "{{ item }}"
    with_items:
      - discord
      - 1password
      - balenaetcher
      - carbon-copy-cloner
      - fing
      - github
      - iterm2
      - screens
      - synology-chat
      - synology-note-station-client
      - visual-studio-code
      - wireshark
      - yacreader
      - ytmdesktop-youtube-music


