---
- name: Check installed apps
  hosts: all
  tasks:

  - name: Check for "{{ item }}"
    stat:
      path: "/Applications/{{ item }}.app"
    with_items:
      - "GitHub Desktop"
      - "Telegram"
      - "iTerm"
      - "Xcode"
    register: app

  - debug:
      msg: "{{ app['results'][item]['item'] }} is not installed on {{ inventory_hostname }}"
    when: app['results'][item]['stat']['exists'] == False
    with_items:
      - 0
      - 1
      - 2
      - 3



#  - debug:
#      msg: "{{app['results'][0]['invocation']['module_args']['path']}} is not installed"
#    when: app.stat.isdir is not defined
#  - debug:
#      msg: "{{app['results'][1]['invocation']['module_args']['path']}} is not installed"
#    when: app.stat.isdir is not defined
#  - debug:
#      msg: "{{app['results'][2]['invocation']['module_args']['path']}} is not installed"
#    when: app.stat.isdir is not defined