---
- name: Update Mac Config
  hosts: laptop 
  roles:
    - brew
  tasks:

    - name: Install via brew cask
      homebrew_cask: 
        name: "{{ item }}"
      with_items:
        - alfred
        - discord
        - github
        - screens
        - synology-chat
        - synology-note-station-client
        - visual-studio-code
        - yacreader
        - ytmdesktop-youtube-music
      register: result